# Title: File-Hash_Collector
# Generated by: Tony Huynh
# Generated on: 8/22/2020
# Discription: Collect all Files in the C: Directory and creates a CSV for the Computer.
# URL: https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck#:~:text=Sigcheck%20is%20a%20command%2Dline,signature%20details%2C%20including%20certificate%20chains.
.\Sigcheck64.exe -c -h -s 'C:\' | Out-File "C:\$env:COMPUTERNAME.csv" -Encoding utf8 -Force -ErrorAction SilentlyContinue
